### ISSUE TITLE
Question about Macro-AUC

### ISSUE THREAD

**Issue by wanweilin** [lilygeorgescu/AED-SSMTL#11]
I noticed that the tags of the 8th and 18th test videos in Avenue dataset are all abnormal. Could you explain how to calculate the AUC of these two videos? I'm confused about this

**Comment by lilygeorgescu** [comment]
Hi,

In order to compute the micro-AUC, there is no issue. For the macro-AUC, we added a 'normal' label at the beginning of the predicted and ground-truth labels for the videos without normal labels.

I personally do recommend reporting the micro-AUC score and the TBDC and TBDC introduced by Ramachandra et al.

Best,
Lili

**Comment by wanweilin** [comment]
Your answer helped me a lot, thanks!
