### ISSUE TITLE
I submitted the signed agreement but didn't get the code!

### ISSUE THREAD

**Issue by dr-smgad** [lilygeorgescu/AED-SSMTL#2]
Hi,

I am willing to get access to the source code for pure academic research purposes. I signed the agreement and sent it by my academic email from 3 weeks now, yet I didn't get any reply!

**Comment by lilygeorgescu** [comment]
Hi,

Apologize for our late response, please note that all the fields in the form are mandatory.
Please revise the form and send back to us.

Best

**Comment by EdwardLocke** [comment]
Hello.sir! 

I’m writing with regard to the application for your source code that I have submitted on November 18, 2021. It’s been a week since my application, and I still haven’t received any updates, so I’m just wondering if you would be kind enough to provide some help. 

Btw, the code  will be only used for my academic research, and I’ve signed the agreement and attached it to the email. 

Many thanks to your help!

**Comment by lilygeorgescu** [comment]
Hi,

I was out of the office lately, I will start going through my email today.

Best,
Lili
